// Generated by gencpp from file rsp_msgs/Move.msg
// DO NOT EDIT!


#ifndef RSP_MSGS_MESSAGE_MOVE_H
#define RSP_MSGS_MESSAGE_MOVE_H

#include <ros/service_traits.h>


#include <rsp_msgs/MoveRequest.h>
#include <rsp_msgs/MoveResponse.h>


namespace rsp_msgs
{

struct Move
{

typedef MoveRequest Request;
typedef MoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Move
} // namespace rsp_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rsp_msgs::Move > {
  static const char* value()
  {
    return "57a5ee7dbb9c528e1eb4e1fa13982317";
  }

  static const char* value(const ::rsp_msgs::Move&) { return value(); }
};

template<>
struct DataType< ::rsp_msgs::Move > {
  static const char* value()
  {
    return "rsp_msgs/Move";
  }

  static const char* value(const ::rsp_msgs::Move&) { return value(); }
};


// service_traits::MD5Sum< ::rsp_msgs::MoveRequest> should match 
// service_traits::MD5Sum< ::rsp_msgs::Move > 
template<>
struct MD5Sum< ::rsp_msgs::MoveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rsp_msgs::Move >::value();
  }
  static const char* value(const ::rsp_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsp_msgs::MoveRequest> should match 
// service_traits::DataType< ::rsp_msgs::Move > 
template<>
struct DataType< ::rsp_msgs::MoveRequest>
{
  static const char* value()
  {
    return DataType< ::rsp_msgs::Move >::value();
  }
  static const char* value(const ::rsp_msgs::MoveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rsp_msgs::MoveResponse> should match 
// service_traits::MD5Sum< ::rsp_msgs::Move > 
template<>
struct MD5Sum< ::rsp_msgs::MoveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rsp_msgs::Move >::value();
  }
  static const char* value(const ::rsp_msgs::MoveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rsp_msgs::MoveResponse> should match 
// service_traits::DataType< ::rsp_msgs::Move > 
template<>
struct DataType< ::rsp_msgs::MoveResponse>
{
  static const char* value()
  {
    return DataType< ::rsp_msgs::Move >::value();
  }
  static const char* value(const ::rsp_msgs::MoveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RSP_MSGS_MESSAGE_MOVE_H
