// Generated by gencpp from file rsp_msgs/ReconfigRequest.msg
// DO NOT EDIT!


#ifndef RSP_MSGS_MESSAGE_RECONFIGREQUEST_H
#define RSP_MSGS_MESSAGE_RECONFIGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rsp_msgs
{
template <class ContainerAllocator>
struct ReconfigRequest_
{
  typedef ReconfigRequest_<ContainerAllocator> Type;

  ReconfigRequest_()
    : configuration(0)  {
    }
  ReconfigRequest_(const ContainerAllocator& _alloc)
    : configuration(0)  {
  (void)_alloc;
    }



   typedef int16_t _configuration_type;
  _configuration_type configuration;





  typedef boost::shared_ptr< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReconfigRequest_

typedef ::rsp_msgs::ReconfigRequest_<std::allocator<void> > ReconfigRequest;

typedef boost::shared_ptr< ::rsp_msgs::ReconfigRequest > ReconfigRequestPtr;
typedef boost::shared_ptr< ::rsp_msgs::ReconfigRequest const> ReconfigRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rsp_msgs::ReconfigRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rsp_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rsp_msgs': ['/home/kaiyu/Dropbox/College/Grad/RSP/git_repos/530_707_independent_project/ros_workspace/src/rsp_pkg/rsp_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b40ab8903a7a68efa497e5baaa3a6f4";
  }

  static const char* value(const ::rsp_msgs::ReconfigRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b40ab8903a7a68eULL;
  static const uint64_t static_value2 = 0xfa497e5baaa3a6f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rsp_msgs/ReconfigRequest";
  }

  static const char* value(const ::rsp_msgs::ReconfigRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 configuration\n\
";
  }

  static const char* value(const ::rsp_msgs::ReconfigRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.configuration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReconfigRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rsp_msgs::ReconfigRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rsp_msgs::ReconfigRequest_<ContainerAllocator>& v)
  {
    s << indent << "configuration: ";
    Printer<int16_t>::stream(s, indent + "  ", v.configuration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RSP_MSGS_MESSAGE_RECONFIGREQUEST_H
